apiVersion: v1 
kind: Service 
metadata: 
  name: marlon-loadbalancer-service 
  namespace: marlon-eks-activity 
spec: 
  type: LoadBalancer 
  selector: 
    app: httpd-app 
  ports: 
    - protocol: TCP 
      port: 80 
      targetPort: 5678